name: master

on:
  push:
    branches:
      - master

jobs:
  download-cross-workflow-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Display master info
        run: |
          # "Merge commit" (in this case) means the commit on master when it get merged
          echo "Previous commit on master - ${{ github.event.before }}"
          echo "Merge commit - ${{ github.event.after }}"
          echo "Merge commit - ${{ github.sha }}"
          echo "Merge commit - $GITHUB_SHA"
          echo "Repo - $GITHUB_REPOSITORY"
      # Since we can't retrieve pr number/ pr branch via Github context object on `push` event,
      # we have to use the commit above to get associate pr info first,
      # then use the pr number/ pr branch in the info to download artifact.
      - name: Get PR info
        id: get_pr_info
        uses: actions/github-script@v4
        with:
          script: |
            const path = require('path');
            const scriptPath = path.resolve('./.github/workflows/dependabot-comments/utils.js');
            const { getPrInfo } = require(scriptPath);

            // access `$GITHUB_SHA` in runner scope === access `process.env.GITHUB_SHA` in the github-script
            const commitHash = process.env.GITHUB_SHA;
            const prInfo = await getPrInfo(github, context, core, commitHash);
            console.log("pr info", prInfo);
            core.setOutput("prNumber", prInfo.number);
      - name: Display PR info
        run: |
          echo "PR outputs - ${{ steps.get_pr_info.outputs }}"
          echo "PR number - ${{ steps.get_pr_info.outputs.prNumber }}"
      - name: Download artifact once PR merged
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: pr.yml
          name: first-data-arctifact
          pr: ${{ steps.get_pr_info.outputs.prNumber }}
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: .
      - name: Collect data
        id: collect_data
        run: echo "::set-output name=downloadedData::$(node ./.github/workflows/download-cross-workflow-artifact.js)"
      - name: Post results to Log console
        run: echo "The downloaded ramdom number is ${{ steps.collect_data.outputs.downloadedData }}"
  # Ref: https://github.community/t/run-github-actions-job-only-if-previous-job-has-failed/174786/2
  # success-job:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Succeed
  #       run: |
  #         exit 0
  failed-job:
    runs-on: ubuntu-latest
    steps:
      - name: Failed
        run: |
          exit 1
  backup-job:
    runs-on: ubuntu-latest
    needs: [failed-job]
    if: always() && needs.failed-job.result == 'failure'
    steps:
      - name: Run if dependent job failed
        run: |
          echo "Backup job running"
